name: Application Release Automation
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Build package it-fse-gtw-fhir-mapping-engine with Maven
      run: mvn --batch-mode --update-snapshots package -DskipTests=true

    - name: Staging packages and source-code
      run: mkdir staging && cp ./target/*.jar staging

    - name: Create release by ncipollo
      uses: ncipollo/release-action@v1
      with:
        artifacts: "staging/*.jar"
        tag: ${{ github.ref_name }}
        commit: "main"
        allowUpdates: true